version: "3.8"
services:
  multiarch-dev:
    build: .
    image: multiarch-dev
    stdin_open: true
    tty: true
    working_dir: /shared
    entrypoint: ["tmux", "new-session", "-A", "-s", "pwnbox", "/root/init"]
    volumes:
      - ./shared:/shared
