#!/bin/bash
# -*- coding: utf-8 -*-

printf '%s\n' \
'  __  __       _ _   _                _           _____                 ____            ' \
' |  \/  |     | | | (_)              | |         |  __ \               |  _ \           ' \
' | \  / |_   _| | |_ _  __ _ _ __ ___| |__ ______| |__) |_      ___ __ | |_) | _____  __' \
' | |\/| | | | | | __| |/ _` | '\''__\ __| '\''_ \______|  ___/\ \ /\ / / '\''_ \|  _ < / _ \ \/ /' \
' | |  | | |_| | | |_| | (_| | | | (__| | | |     | |     \ V  V /| | | | |_) | (_) >  < ' \
' |_|  |_|\__,_|_|\__|_|\__,_|_|  \___|_| |_|     |_|      \_/\_/ |_| |_|____/ \___/_/\_\ ' \
'                                                                                        ' \
'                ⚙  Multiarch-PwnBox: Pwning Across Architectures  ⚙' \
'' \
'     ░ Supports x86 / ARM / MIPS / RISC-V' \
'     ░ Automatic QEMU + GDB Multiarch Debugging' \
'     ░ Pwntools integration ready' \
'     ░ Lightweight, scriptable, hacker-friendly' \
'' \
'-------------------------------------------------------------------------' \
'|  Usage: see examples python codes ;)                                  |' \
'|  Visit: https://github.com/arthubhub/Multiarch-PwnBox                 |' \
'-------------------------------------------------------------------------' \
'' \
'              Happy pwning! 🐚 Exploit. Debug. Reverse. Repeat.'

# Enfin on reste sur un shell interactif
exec /bin/bash